/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions/$sessionId'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects/new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as DashboardPProjectIdRouteRouteImport } from './routes/dashboard/p/$projectId/route'
import { Route as DashboardPProjectIdIndexRouteImport } from './routes/dashboard/p/$projectId/index'
import { Route as DashboardPProjectIdApprovalsRouteImport } from './routes/dashboard/p/$projectId/approvals'
import { Route as DashboardPProjectIdSessionsIndexRouteImport } from './routes/dashboard/p/$projectId/sessions/index'
import { Route as DashboardPProjectIdWorktreesWorktreeIdRouteImport } from './routes/dashboard/p/$projectId/worktrees/$worktreeId'
import { Route as DashboardPProjectIdSessionsSessionIdRouteImport } from './routes/dashboard/p/$projectId/sessions/$sessionId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPProjectIdRouteRoute =
  DashboardPProjectIdRouteRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPProjectIdIndexRoute =
  DashboardPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPProjectIdRouteRoute,
  } as any)
const DashboardPProjectIdApprovalsRoute =
  DashboardPProjectIdApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => DashboardPProjectIdRouteRoute,
  } as any)
const DashboardPProjectIdSessionsIndexRoute =
  DashboardPProjectIdSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => DashboardPProjectIdRouteRoute,
  } as any)
const DashboardPProjectIdWorktreesWorktreeIdRoute =
  DashboardPProjectIdWorktreesWorktreeIdRouteImport.update({
    id: '/worktrees/$worktreeId',
    path: '/worktrees/$worktreeId',
    getParentRoute: () => DashboardPProjectIdRouteRoute,
  } as any)
const DashboardPProjectIdSessionsSessionIdRoute =
  DashboardPProjectIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardPProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/p/$projectId': typeof DashboardPProjectIdRouteRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/p/$projectId/approvals': typeof DashboardPProjectIdApprovalsRoute
  '/dashboard/p/$projectId/': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/sessions/$sessionId': typeof DashboardPProjectIdSessionsSessionIdRoute
  '/dashboard/p/$projectId/worktrees/$worktreeId': typeof DashboardPProjectIdWorktreesWorktreeIdRoute
  '/dashboard/p/$projectId/sessions/': typeof DashboardPProjectIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/p/$projectId/approvals': typeof DashboardPProjectIdApprovalsRoute
  '/dashboard/p/$projectId': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/sessions/$sessionId': typeof DashboardPProjectIdSessionsSessionIdRoute
  '/dashboard/p/$projectId/worktrees/$worktreeId': typeof DashboardPProjectIdWorktreesWorktreeIdRoute
  '/dashboard/p/$projectId/sessions': typeof DashboardPProjectIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/events': typeof ApiEventsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/p/$projectId': typeof DashboardPProjectIdRouteRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/p/$projectId/approvals': typeof DashboardPProjectIdApprovalsRoute
  '/dashboard/p/$projectId/': typeof DashboardPProjectIdIndexRoute
  '/dashboard/p/$projectId/sessions/$sessionId': typeof DashboardPProjectIdSessionsSessionIdRoute
  '/dashboard/p/$projectId/worktrees/$worktreeId': typeof DashboardPProjectIdWorktreesWorktreeIdRoute
  '/dashboard/p/$projectId/sessions/': typeof DashboardPProjectIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/events'
    | '/dashboard/'
    | '/dashboard/p/$projectId'
    | '/api/trpc/$'
    | '/dashboard/projects/new'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/p/$projectId/approvals'
    | '/dashboard/p/$projectId/'
    | '/dashboard/p/$projectId/sessions/$sessionId'
    | '/dashboard/p/$projectId/worktrees/$worktreeId'
    | '/dashboard/p/$projectId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/dashboard'
    | '/api/trpc/$'
    | '/dashboard/projects/new'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/p/$projectId/approvals'
    | '/dashboard/p/$projectId'
    | '/dashboard/p/$projectId/sessions/$sessionId'
    | '/dashboard/p/$projectId/worktrees/$worktreeId'
    | '/dashboard/p/$projectId/sessions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/events'
    | '/dashboard/'
    | '/dashboard/p/$projectId'
    | '/api/trpc/$'
    | '/dashboard/projects/new'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/p/$projectId/approvals'
    | '/dashboard/p/$projectId/'
    | '/dashboard/p/$projectId/sessions/$sessionId'
    | '/dashboard/p/$projectId/worktrees/$worktreeId'
    | '/dashboard/p/$projectId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sessions/$sessionId': {
      id: '/dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p/$projectId': {
      id: '/dashboard/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/dashboard/p/$projectId'
      preLoaderRoute: typeof DashboardPProjectIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/p/$projectId/': {
      id: '/dashboard/p/$projectId/'
      path: '/'
      fullPath: '/dashboard/p/$projectId/'
      preLoaderRoute: typeof DashboardPProjectIdIndexRouteImport
      parentRoute: typeof DashboardPProjectIdRouteRoute
    }
    '/dashboard/p/$projectId/approvals': {
      id: '/dashboard/p/$projectId/approvals'
      path: '/approvals'
      fullPath: '/dashboard/p/$projectId/approvals'
      preLoaderRoute: typeof DashboardPProjectIdApprovalsRouteImport
      parentRoute: typeof DashboardPProjectIdRouteRoute
    }
    '/dashboard/p/$projectId/sessions/': {
      id: '/dashboard/p/$projectId/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/p/$projectId/sessions/'
      preLoaderRoute: typeof DashboardPProjectIdSessionsIndexRouteImport
      parentRoute: typeof DashboardPProjectIdRouteRoute
    }
    '/dashboard/p/$projectId/worktrees/$worktreeId': {
      id: '/dashboard/p/$projectId/worktrees/$worktreeId'
      path: '/worktrees/$worktreeId'
      fullPath: '/dashboard/p/$projectId/worktrees/$worktreeId'
      preLoaderRoute: typeof DashboardPProjectIdWorktreesWorktreeIdRouteImport
      parentRoute: typeof DashboardPProjectIdRouteRoute
    }
    '/dashboard/p/$projectId/sessions/$sessionId': {
      id: '/dashboard/p/$projectId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/p/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof DashboardPProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof DashboardPProjectIdRouteRoute
    }
  }
}

interface DashboardPProjectIdRouteRouteChildren {
  DashboardPProjectIdApprovalsRoute: typeof DashboardPProjectIdApprovalsRoute
  DashboardPProjectIdIndexRoute: typeof DashboardPProjectIdIndexRoute
  DashboardPProjectIdSessionsSessionIdRoute: typeof DashboardPProjectIdSessionsSessionIdRoute
  DashboardPProjectIdWorktreesWorktreeIdRoute: typeof DashboardPProjectIdWorktreesWorktreeIdRoute
  DashboardPProjectIdSessionsIndexRoute: typeof DashboardPProjectIdSessionsIndexRoute
}

const DashboardPProjectIdRouteRouteChildren: DashboardPProjectIdRouteRouteChildren =
  {
    DashboardPProjectIdApprovalsRoute: DashboardPProjectIdApprovalsRoute,
    DashboardPProjectIdIndexRoute: DashboardPProjectIdIndexRoute,
    DashboardPProjectIdSessionsSessionIdRoute:
      DashboardPProjectIdSessionsSessionIdRoute,
    DashboardPProjectIdWorktreesWorktreeIdRoute:
      DashboardPProjectIdWorktreesWorktreeIdRoute,
    DashboardPProjectIdSessionsIndexRoute:
      DashboardPProjectIdSessionsIndexRoute,
  }

const DashboardPProjectIdRouteRouteWithChildren =
  DashboardPProjectIdRouteRoute._addFileChildren(
    DashboardPProjectIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPProjectIdRouteRoute: typeof DashboardPProjectIdRouteRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPProjectIdRouteRoute: DashboardPProjectIdRouteRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiEventsRoute: ApiEventsRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
